jasypt:
  encryptor:
    password: 1234
    bean: jasyptStringEncryptor

spring:
  mvc:
    view:
      suffix: .html , .mustache
    hiddenmethod:
      filter:
        enabled: true  # html form _> REST API 사용하기 위해 설정 spring boot 2.2 부터 직접 설정해 줘야함
  profiles:
    include: oauth
  output:
    ansi.enabled: always
  datasource:
    url: jdbc:h2:mem:68546e49-4775-42ea-b52b-8c0bec05dcc1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
